error message

diff --git a/.local/bin/sh/bar-btc b/.local/bin/sh/bar-btc
--- a/.local/bin/sh/bar-btc
+++ b/.local/bin/sh/bar-btc
@@ -1,2 +1,13 @@
 #!/bin/sh
-BTC=$(curl -Ls "https://gbp.rate.sx/1btc" 2> /dev/null) && echo "$BTC" | cut -d "." -f1 || echo "N/A"
+#BTC=$(curl -Ls "https://gbp.rate.sx/1btc" 2> /dev/null) && echo "$BTC" | cut -d "." -f1 || echo "N/A"
+
+BTC=$(curl -Ls "https://gbp.rate.sx/1xmr") 2> /dev/null
+
+case $BTC in
+	*"DOCTYPE"*)
+		echo "ERROR"
+		;;
+	*) echo "$BTC" | cut -d "." -f1
+		;;
+esac
+
diff --git a/.local/bin/sh/bar-xmr b/.local/bin/sh/bar-xmr
--- a/.local/bin/sh/bar-xmr
+++ b/.local/bin/sh/bar-xmr
@@ -1,2 +1,13 @@
 #!/bin/sh
-XMR=$(curl -Ls "https://gbp.rate.sx/1xmr" 2> /dev/null) && echo "$XMR" | cut -d "." -f1 || echo "N/A"
+#XMR=$(curl -Ls "https://gbp.rate.sx/1xmr" 2> /dev/null) && echo "$XMR" | cut -d "." -f1 || echo "N/A"
+
+XMR=$(curl -Ls "https://gbp.rate.sx/1xmr") 2> /dev/null
+
+case $XMR in
+	*"DOCTYPE"*)
+		echo "ERROR"
+		;;
+	*) echo "$XMR" | cut -d "." -f1
+		;;
+esac
+
